/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package report;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;   
import koneksi.Barang;
/**
 *
 * @author fadly
 */
public class ReportBarang extends javax.swing.JPanel {
    private static final String DB_URL = "jdbc:mysql://localhost:3306/project_inventory";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "";
    Connection conn;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ReportBarang
     */
    public ReportBarang() {
        initComponents();
        connectToDB();
        loadData();
    }
        
    // Method to establish database connection
    private void connectToDB() {
        try {
            conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + e.getMessage());
        }
    }
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel(new String[]{
                "Kode Barang", "Nama Barang", "Berat", "Kode Supplier", "Nama Supplier",
                "Stok Awal", "Harga Beli", "Harga Jual", "Satuan"}, 0);

        try (Connection c = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             Statement s = c.createStatement();
             ResultSet r = s.executeQuery("SELECT * FROM tb_barang")) {

            while (r.next()) {
                String kodeBarang = r.getString("kodeBarang");
                String namaBarang = r.getString("namaBarang");
                String berat = r.getString("berat");
                String kodeSupplier = r.getString("kodeSupplier");
                String namaSupplier = r.getString("namaSupplier");
                int stokAwal = r.getInt("StokAwal");
                double hargaBeli = r.getDouble("hargaBeli");
                double hargaJual = r.getDouble("hargaJual");
                String satuan = r.getString("satuan");

                model.addRow(new Object[]{
                        kodeBarang, namaBarang, berat, kodeSupplier, namaSupplier,
                        stokAwal, hargaBeli, hargaJual, satuan});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        tblReport.setModel(model);
    }

    // Helper method to get the connection object
    private Connection getConnection() {
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_report = new javax.swing.JPanel();
        txtPencarianBarang = new javax.swing.JTextField();
        btnPencarian = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(953, 796));
        setLayout(new java.awt.CardLayout());

        panel_report.setBackground(new java.awt.Color(153, 153, 153));

        txtPencarianBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPencarianBarangActionPerformed(evt);
            }
        });

        btnPencarian.setText("Pencarian");
        btnPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPencarianActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang ", "Nama Barang ", "Berat", "Kode Supplier ", "Nama Supplier", "QTY", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Report Barang");
        jLabel3.setMaximumSize(new java.awt.Dimension(161, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(161, 29));
        jLabel3.setPreferredSize(new java.awt.Dimension(161, 29));

        javax.swing.GroupLayout panel_reportLayout = new javax.swing.GroupLayout(panel_report);
        panel_report.setLayout(panel_reportLayout);
        panel_reportLayout.setHorizontalGroup(
            panel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(panel_reportLayout.createSequentialGroup()
                        .addComponent(txtPencarianBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_reportLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_reportLayout.setVerticalGroup(
            panel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPencarian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPencarianBarang, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panel_report, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtPencarianBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarianBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPencarianBarangActionPerformed

    private void btnPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianActionPerformed
        String keyword = txtPencarianBarang.getText().trim();

        // Query SQL untuk mencari barang berdasarkan nama
        String sql = "SELECT * FROM tb_barang WHERE namaBarang LIKE ?";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, "%" + keyword + "%");

            ResultSet rs = stmt.executeQuery();

            // Menampilkan hasil ke tabel tblReport
            DefaultTableModel model = new DefaultTableModel(new String[]{
                    "Kode Barang", "Nama Barang", "Berat", "Kode Supplier", "Nama Supplier",
                    "Stok Awal", "Harga Beli", "Harga Jual", "Satuan"}, 0);

            while (rs.next()) {
                String kodeBarang = rs.getString("kodeBarang");
                String namaBarang = rs.getString("namaBarang");
                String berat = rs.getString("berat");
                String kodeSupplier = rs.getString("kodeSupplier");
                String namaSupplier = rs.getString("namaSupplier");
                int stokAwal = rs.getInt("StokAwal");
                double hargaBeli = rs.getDouble("hargaBeli");
                double hargaJual = rs.getDouble("hargaJual");
                String satuan = rs.getString("satuan");

                model.addRow(new Object[]{
                        kodeBarang, namaBarang, berat, kodeSupplier, namaSupplier,
                        stokAwal, hargaBeli, hargaJual, satuan});
            }

            tblReport.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPencarianActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        
    }//GEN-LAST:event_btnCetakActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnPencarian;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_report;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtPencarianBarang;
    // End of variables declaration//GEN-END:variables
}